-- discord.db
ALTER TABLE ranked_lobby ADD COLUMN dt BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ranked_lobby ADD COLUMN scorev2 BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user DROP COLUMN score_preference;
